// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDWSSfIzepJ_xV67B2UQfKVUVJSRdnqvc',
    appId: '1:4387457014:web:6fa874a42566a8de5569d7',
    messagingSenderId: '4387457014',
    projectId: 'mobdev-finalproj',
    authDomain: 'mobdev-finalproj.firebaseapp.com',
    storageBucket: 'mobdev-finalproj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA_3xsbsT7JX-IBs3xr-WYk1VX6_B9k1E',
    appId: '1:4387457014:android:97756a01609c0f905569d7',
    messagingSenderId: '4387457014',
    projectId: 'mobdev-finalproj',
    storageBucket: 'mobdev-finalproj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPxk-qiFuFyyR6afULCNhcrBIccnpbIVs',
    appId: '1:4387457014:ios:b97b4b629d03a2a75569d7',
    messagingSenderId: '4387457014',
    projectId: 'mobdev-finalproj',
    storageBucket: 'mobdev-finalproj.appspot.com',
    iosBundleId: 'com.example.mobdevFinalproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPxk-qiFuFyyR6afULCNhcrBIccnpbIVs',
    appId: '1:4387457014:ios:8fd66c549eed887e5569d7',
    messagingSenderId: '4387457014',
    projectId: 'mobdev-finalproj',
    storageBucket: 'mobdev-finalproj.appspot.com',
    iosBundleId: 'com.example.mobdevFinalproj.RunnerTests',
  );
}
